version: '3'

services:
    redis-server:
        container_name: redis-server
        image: redis
        ports:
            - 6379:6379
        networks:
            - redisnet

networks:
    redisnet:
        driver: bridge